name: docfx-unitypackage

on:
  push:
    branches:
      - main

jobs:
  # Build the documentation
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      # This step needs to happen before anything else!
      - name: Move everything inside the manual/ folder.
        run: |
          mkdir -p manual
          mv -v Documentation~/* manual/
          mv -v manual Documentation~/manual

      - name: Generate index page
        run: echo 'This page redirects to the [manual](manual/).' > Documentation~/index.md

      - name: Generate main Table of Contents
        run: |
          echo '- name: Manual
            href: manual/
          - name: Scripting API
            href: api/
            homepage: api/index.md
          - name: Changelog
            href: changelog/
            homepage: changelog/CHANGELOG.md
          - name: License
            href: license/
            homepage: license/LICENSE.md' > Documentation~/toc.yml

      # Replace * and 5 consecutive spaces with # in the Table of Contents to convert Unity's format to DocFX's format.
      - name: Generate manual Table of Contents
        run: |
          if [ -f Documentation~/manual/TableOfContents.md ]; then
            mv Documentation~/manual/TableOfContents.md Documentation~/manual/toc.md
          fi
          if [ -f Documentation~/manual/toc.md ]; then
            sed -i -e 's/*/#/g' Documentation~/manual/toc.md
            sed -i -e 's/     /#/g' Documentation~/manual/toc.md
          fi

      - name: Generate api index
        run: |
          mkdir -p Documentation~/api
          if [ -f Documentation~/api_index.md ]; then
            cp Documentation~/api_index.md Documentation~/api/index.md
            rm Documentation~/api_index.md
          else
            echo 'This is the documentation for the Scripting APIs of this package.' > Documentation~/api/index.md
          fi

      - name: Generate changelog page
        run: |
          mkdir -p Documentation~/changelog
          cp CHANGELOG.md Documentation~/changelog/CHANGELOG.md
          echo '# [Changes](CHANGELOG.md)' > Documentation~/changelog/toc.md

      - name: Generate license page
        run: |
          mkdir -p Documentation~/license
          cp LICENSE.md Documentation~/license/LICENSE.md
          echo '# [License](LICENSE.md)' > Documentation~/license/toc.md
          if [ -f 'Third Party Notices.md' ]; then
            cp 'Third Party Notices.md' 'Documentation~/license/Third Party Notices.md'
            sed -i '1i# [Third Party Notices](Third Party Notices.md)' Documentation~/license/toc.md
          fi

      - name: Read package.json
        run: |
          content=`cat package.json`
          echo 'package<<EOF' >> $GITHUB_ENV
          echo $content >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Generate docfx.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          url=$(gh api "repos/$GITHUB_REPOSITORY/pages" --jq '.html_url')
          echo '{
              "metadata": [{
                  "src": [{"src": "..", "files": ["**/*.cs"]}],
                  "globalNamespaceId": "Global",
                  "dest": "api",
                  "allowCompilationErrors": true
              }],
              "build": {
                  "globalMetadata": {
                      "_appTitle": "'${{ fromJson(env.package).displayName }}'",
                      "_appFooter": "<span>Made by <a href=\"https://github.com/'$GITHUB_REPOSITORY_OWNER'\" target=\"_blank\">'$GITHUB_REPOSITORY_OWNER'</a> using <a href=\"https://dotnet.github.io/docfx\" target=\"_blank\">DocFX</a></span>",
                      "_enableSearch": true,
                      "_disableContribution": true
                      "_disableNextArticle": true
                  },
                  "fileMetadata": {
                      "_disableContribution": {"manual/**/*.md": false}
                  },
                  "content": [
                      {"files": ["index.md", "toc.yml"]},
                      {"src": "license", "files": ["*.md"], "dest": "license"},
                      {"src": "changelog", "files": ["*.md"], "dest": "changelog"},
                      {"src": "api", "files": ["*.yml", "index.md"], "dest": "api"},
                      {"src": "manual", "files": ["*.md"], "dest": "manual"}
                  ],
                  "resource": [{"files": ["manual/images/*"]}],
                  "template": ["default", "modern"],
                  "sitemap": {"baseUrl": "'$url'"},
                  "xref": ["'$url'"],
                  "xrefService": ["https://xref.docs.microsoft.com/query?uid={uid}"],
                  "dest": "../_site"
              }
          }' > Documentation~/docfx.json
          if [ -f Documentation~/manual/filter.yml ]; then
            sed -i '5i\        "filter": "manual/filter.yml",' Documentation~/docfx.json
          fi
          if [ ! -f Documentation~/manual.toc.md ]; then
            sed -i '17i\            "_disableToc": {"manual/**/*.md": false},' Documentation~/docfx.json
            sed -i '17i\            "_layout": {"manual/**/*.md": "chromeless"},'  Documentation~/docfx.json
          fi

      - name: Dotnet Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      
      - run: dotnet tool update -g docfx

      - name: Build
        run: docfx Documentation~/docfx.json

      # Generate a redirect to the manual/ page, taking protocol and custom domain names into account.
      - name: Generate redirect
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          url=$(gh api "repos/$GITHUB_REPOSITORY/pages" --jq '.html_url')
          sed -i '19i\      <meta http-equiv="refresh" content="0;URL='"$url"manual/'">' _site/index.html

      # Upload the generated documentation
      - name: Upload site artifact
        uses: actions/upload-artifact@v1
        with:
          name: _site
          path: _site # Must equals the 'build.dest' value on your docfx.json

  # Deploy the generated documentation to the gh-pages branch
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      # Download the generated documentation
      - name: Download site artifact
        uses: actions/download-artifact@v1
        with:
          name: _site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _site