name: Build DocFX Documentation

on:
  push:
    branches:
      - main

jobs:
  # Build the documentation
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # with:
        #   submodules: true

      - name: Generate changelog page
        run: |
          mkdir -p Documentation~\changelog
          cp CHANGELOG.md Documentation~\changelog\CHANGELOG.md
          echo '# [Changes](CHANGELOG.md)' > Documentation~\changelog\toc.md

      - name: Generate license page
        run: |
          mkdir -p Documentation~\license
          cp LICENSE.md Documentation~\license\LICENSE.md
          echo '# [License](LICENSE.md)' > Documentation~\license\toc.md

      - name: Generate main Table of Contents
        run: |
          echo '# [Manual](manual//)' > Documentation~\toc.md
          echo '# [Scripting API](api//)' >> Documentation~\toc.md
          echo '# [Changelog](changelog//)' >> Documentation~\toc.md
          echo '# [License](license//)' >> Documentation~\toc.md

      - name: Add api index
        # shell: bash
        run: |
          mkdir -p Documentation~\api
          echo 'This is the documentation for the Scripting APIs of this package.' > Documentation~\api\index.md

      # - name: Install DocFX
      #   run: choco install -y docfx

      - name: Dotnet Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      
      - run: dotnet tool update -g docfx

      - name: Build
        run: docfx Documentation~/docfx.json

      # Upload the generated documentation
      - name: Upload site artifact
        uses: actions/upload-artifact@v1
        with:
          name: _site
          path: _site # Must equals the 'build.dest' value on your docfx.json

  # Deploy the generated documentation to the gh-pages branch
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # with:
        #   submodules: true

      # Download the generated documentation
      - name: Download site artifact
        uses: actions/download-artifact@v1
        with:
          name: _site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _site